<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DekorasiRumahTextLabel</name>
   <tag></tag>
   <elementGuidId>e601d834-e35a-42d5-b5ed-575537531655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h1[@class='title'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h1[@class='title'])[1]</value>
      <webElementGuid>fcef555a-225c-4cc0-9691-18b63141b55f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
